export const categories = [
    {
        id: 'food-beverage',
        name: 'FOOD & BEVERAGE',
        subCategories: [
            {
                id: 'fruits',
                name: 'Fruits',
                items: ['Fresh Fruits', 'Organic Fruits', 'Tropical Fruits', 'Local Fruits', 'Dried Fruits'],
            },
            {
                id: 'vegetables',
                name: 'Vegetables',
                items: ['Fresh Vegetables', 'Organic Vegetables', 'Leafy Greens', 'Root Vegetables', 'Local Produce'],
            },
            {
                id: 'grains',
                name: 'Grains',
                items: ['Whole Grains', 'Ancient Grains', 'Organic Grains', 'Rice Varieties', 'Quinoa & Amaranth'],
            },
            {
                id: 'nuts-seeds',
                name: 'Nuts & Seeds',
                items: ['Raw Nuts', 'Roasted Nuts', 'Mixed Seeds', 'Nut Butters', 'Trail Mixes'],
            },
            {
                id: 'beverages',
                name: 'Beverages',
                items: ['Herbal Tea', 'Green Tea', 'Black Tea', 'Organic Coffee', 'Specialty Coffee', 'Cold-Pressed Juices', 'Fresh Juices'],
            },
            {
                id: 'snacks',
                name: 'Snacks',
                items: ['Healthy Snacks', 'Protein Snacks', 'Gluten-Free Snacks', 'Energy Bars', 'Dried Fruits & Nuts'],
            },
        ],
    },
    {
        id: 'health-wellness',
        name: 'HEALTH & WELLNESS',
        subCategories: [
            {
                id: 'supplements',
                name: 'Supplements',
                items: ['Daily Multivitamins', 'Specialty Vitamins', 'Sports Supplements', 'Pre-Workout', 'Post-Workout'],
            },
            {
                id: 'protein',
                name: 'Protein',
                items: ['Plant-Based Protein', 'Whey Protein', 'Vegan Protein', 'Protein Bars', 'Protein Shakes'],
            },
            {
                id: 'superfoods',
                name: 'Superfoods',
                items: ['Organic Superfoods', 'Superfood Powders', 'Traditional Herbs', 'Herbal Extracts', 'Green Superfoods'],
            },
            {
                id: 'essential-oils',
                name: 'Essential Oils',
                items: ['Pure Essential Oils', 'Essential Oil Blends', 'Therapeutic Oils', 'Massage Oils', 'Aromatherapy Kits'],
            },
            {
                id: 'fitness',
                name: 'Fitness',
                items: [
                    'Premium Yoga Mats',
                    'Yoga Accessories',
                    'Meditation Accessories',
                    'Meditation Cushions',
                    'Home Fitness Equipment',
                    'Resistance Bands',
                    'Fitness Trackers',
                    'Recovery Tools',
                ],
            },
        ],
    },
    {
        id: 'personal-care',
        name: 'PERSONAL CARE',
        subCategories: [
            {
                id: 'hair-care',
                name: 'Hair Care',
                items: [
                    'Natural Shampoo',
                    'Color-Safe Shampoo',
                    'Organic Conditioner',
                    'Deep Conditioning',
                    'Natural Hair Care',
                    'Hair Styling Products',
                ],
            },
            {
                id: 'skin-care',
                name: 'Skin Care',
                items: [
                    'Anti-Aging Face Cream',
                    'Moisturizing Face Cream',
                    'Gentle Face Wash',
                    'Exfoliating Face Wash',
                    'Natural Skincare Sets',
                    'Anti-Aging Sets',
                    'Acne Treatment Sets',
                ],
            },
            {
                id: 'body-care',
                name: 'Body Care',
                items: [
                    'Eco-Friendly Body Wash',
                    'Natural Soap Bars',
                    'Natural Deodorant',
                    'Crystal Deodorant',
                    'Natural Body Care',
                    'Foot Care Products',
                ],
            },
            {
                id: 'oral-care',
                name: 'Oral Care',
                items: ['Organic Toothpaste', 'Natural Mouthwash', 'Dental Floss', 'Toothbrushes', 'Oral Care Kits'],
            },
            {
                id: 'makeup',
                name: 'Makeup',
                items: ['Clean Beauty Makeup', 'Natural Foundation', 'Organic Lip Products', 'Natural Mascara', 'Mineral Makeup'],
            },
        ],
    },
    {
        id: 'home-cleaning',
        name: 'HOME CLEANING',
        subCategories: [
            {
                id: 'laundry',
                name: 'Laundry',
                items: ['Natural Laundry Detergent', 'Fabric Softener', 'Stain Removers', 'Laundry Care Kits', 'Dryer Balls'],
            },
            {
                id: 'kitchen-cleaning',
                name: 'Kitchen Cleaning',
                items: ['Plant-Based Dish Soap', 'Dishwasher Detergent', 'Multi-Surface Cleaner', 'Kitchen Cleaning Kits', 'Food Waste Bins'],
            },
            {
                id: 'bathroom-cleaning',
                name: 'Bathroom Cleaning',
                items: ['Bathroom Sanitizer', 'Toilet Cleaner', 'Bathroom Cleaning Kits', 'Shower Cleaners', 'Bathroom Accessories'],
            },
            {
                id: 'floor-cleaning',
                name: 'Floor Cleaning',
                items: ['Non-Toxic Floor Cleaner', 'Wood Floor Cleaner', 'Carpet Cleaners', 'Floor Mops', 'Cleaning Tools'],
            },
            {
                id: 'air-freshening',
                name: 'Air Freshening',
                items: ['Natural Air Freshener', 'Essential Oil Diffusers', 'Odor Eliminators', 'Air Purifiers', 'Scented Candles'],
            },
        ],
    },
    {
        id: 'kitchen-essentials',
        name: 'KITCHEN ESSENTIALS',
        subCategories: [
            {
                id: 'cookware',
                name: 'Cookware',
                items: ['Non-Stick Cookware', 'Stainless Steel Cookware', 'Cast Iron Cookware', 'Ceramic Cookware', 'Cookware Sets'],
            },
            {
                id: 'utensils',
                name: 'Utensils',
                items: ['Stainless Steel Utensils', 'Wooden Utensils', 'Silicone Utensils', 'Cooking Tools', 'Baking Tools'],
            },
            {
                id: 'storage',
                name: 'Storage',
                items: ['Glass Storage Containers', 'BPA-Free Containers', 'Beeswax Food Wraps', 'Silicone Food Covers', 'Storage Solutions'],
            },
            {
                id: 'tableware',
                name: 'Tableware',
                items: ['Ceramic Plates', 'Bamboo Plates', 'Glass Bowls', 'Ceramic Bowls', 'Stainless Steel Cups', 'Glass Cups'],
            },
            {
                id: 'prep-tools',
                name: 'Prep Tools',
                items: ['Bamboo Cutting Boards', 'Wooden Cutting Boards', 'Food Prep Tools', 'Measuring Tools', 'Mixing Bowls'],
            },
        ],
    },
    {
        id: 'baby-kids',
        name: 'BABY & KIDS',
        subCategories: [
            {
                id: 'diapering',
                name: 'Diapering',
                items: ['Eco-Friendly Diapers', 'Cloth Diapers', 'Natural Baby Wipes', 'Sensitive Skin Wipes', 'Diaper Bags'],
            },
            {
                id: 'feeding',
                name: 'Feeding',
                items: ['Organic Baby Food', 'Baby Snacks', 'BPA-Free Bottles', 'Sippy Cups', 'Feeding Accessories'],
            },
            {
                id: 'clothing',
                name: 'Clothing',
                items: ['Organic Clothing', 'Natural Fiber Clothing', 'Onesies', 'Sleepwear', 'Outerwear'],
            },
            {
                id: 'toys',
                name: 'Toys',
                items: ['Educational Toys', 'Developmental Toys', 'Teething Toys', 'Plush Toys', 'Outdoor Toys'],
            },
            {
                id: 'care',
                name: 'Care',
                items: ['Natural Baby Care', 'Baby Skincare', 'Baby Shampoo', 'Baby Lotion', 'Baby First Aid'],
            },
        ],
    },
    {
        id: 'clothing',
        name: 'CLOTHING',
        subCategories: [
            {
                id: 'mens-clothing',
                name: "Men's Clothing",
                items: ['T-Shirts', 'Hoodies', 'Jackets', 'Pants', 'Shorts', 'Socks', 'Underwear', 'Shoes', 'Accessories', 'Bags'],
            },
            {
                id: 'womens-clothing',
                name: "Women's Clothing",
                items: ['T-Shirts', 'Hoodies', 'Jackets', 'Pants', 'Skirts', 'Dresses', 'Socks', 'Underwear', 'Shoes', 'Accessories', 'Bags'],
            },
            {
                id: 'boys-clothing',
                name: "Boys' Clothing",
                items: ['T-Shirts', 'Hoodies', 'Jackets', 'Pants', 'Shorts', 'Socks', 'Underwear', 'Shoes', 'Accessories', 'Bags'],
            },
            {
                id: 'girls-clothing',
                name: "Girls' Clothing",
                items: ['T-Shirts', 'Hoodies', 'Jackets', 'Pants', 'Skirts', 'Dresses', 'Socks', 'Underwear', 'Shoes', 'Accessories', 'Bags'],
            },
            {
                id: 'baby-clothing',
                name: 'Baby Clothing',
                items: ['Onesies', 'Sleepwear', 'Outerwear', 'Pants', 'Socks', 'Shoes', 'Accessories', 'Bags'],
            },
        ],
    },
    {
        id: 'sustainable-living',
        name: 'SUSTAINABLE LIVING',
        subCategories: [
            {
                id: 'water-solutions',
                name: 'Water Solutions',
                items: ['Stainless Steel Bottles', 'Glass Water Bottles', 'Water Filters', 'Rain Barrels', 'Water Conservation Kits'],
            },
            {
                id: 'food-storage',
                name: 'Food Storage',
                items: ['Bento Lunch Boxes', 'Food Containers', 'Glass Food Storage', 'Beeswax Wraps', 'Silicone Food Covers'],
            },
            {
                id: 'shopping',
                name: 'Shopping',
                items: ['Reusable Shopping Bags', 'Produce Bags', 'Silicone Straws', 'Bamboo Straws', 'Shopping Accessories'],
            },
            {
                id: 'composting',
                name: 'Composting',
                items: ['Indoor Compost Bins', 'Outdoor Composters', 'Composting Tools', 'Compost Starters', 'Compost Bags'],
            },
            {
                id: 'energy',
                name: 'Energy',
                items: ['Solar Power Banks', 'Solar Lights', 'LED Light Bulbs', 'Energy Monitors', 'Energy Saving Kits'],
            },
        ],
    },
    {
        id: 'pet-care',
        name: 'PET CARE',
        subCategories: [
            {
                id: 'dog-care',
                name: 'Dog Care',
                items: [
                    'Natural Dog Food',
                    'Grain-Free Dog Food',
                    'Healthy Dog Treats',
                    'Interactive Dog Toys',
                    'Orthopedic Dog Beds',
                    'Eco-Friendly Dog Collars',
                    'Retractable Dog Leashes',
                    'Natural Dog Grooming',
                ],
            },
            {
                id: 'cat-care',
                name: 'Cat Care',
                items: [
                    'Organic Cat Food',
                    'Wet Cat Food',
                    'Healthy Cat Treats',
                    'Interactive Cat Toys',
                    'Cat Beds',
                    'Cat Collars',
                    'Cat Harnesses',
                    'Cat Grooming Kits',
                ],
            },
            {
                id: 'pet-health',
                name: 'Pet Health',
                items: ['Pet Dental Care', 'Pet Supplements', 'Pet First Aid', 'Pet Vitamins', 'Pet Medications'],
            },
            {
                id: 'pet-accessories',
                name: 'Pet Accessories',
                items: ['Pet Travel Accessories', 'Pet Feeding Supplies', 'Pet Beds & Furniture', 'Pet Toys', 'Pet Clothing'],
            },
            {
                id: 'pet-hygiene',
                name: 'Pet Hygiene',
                items: ['Biodegradable Cat Litter', 'Litter Boxes', 'Pet Shampoo', 'Pet Wipes', 'Pet Cleaning Supplies'],
            },
        ],
    },
    {
        id: 'home-textiles',
        name: 'HOME TEXTILES',
        subCategories: [
            {
                id: 'bedding',
                name: 'Bedding',
                items: [
                    'Bed Sheets',
                    'Duvet Covers',
                    'Comforters',
                    'Quilts',
                    'Blankets',
                    'Pillowcases',
                    'Pillow Shams',
                    'Bed Skirts',
                    'Mattress Protectors',
                    'Bed Throws',
                ],
            },
            {
                id: 'bath-textiles',
                name: 'Bath Textiles',
                items: [
                    'Bath Towels',
                    'Hand Towels',
                    'Washcloths',
                    'Bath Mats',
                    'Shower Curtains',
                    'Bath Rugs',
                    'Bathroom Sets',
                    'Beach Towels',
                    'Spa Towels',
                    'Bathroom Accessories',
                ],
            },
            {
                id: 'kitchen-textiles',
                name: 'Kitchen Textiles',
                items: [
                    'Kitchen Towels',
                    'Oven Mitts',
                    'Pot Holders',
                    'Aprons',
                    'Table Runners',
                    'Placemats',
                    'Napkins',
                    'Kitchen Rugs',
                    'Kitchen Curtains',
                    'Kitchen Sets',
                ],
            },
            {
                id: 'curtains-drapes',
                name: 'Curtains & Drapes',
                items: [
                    'Window Curtains',
                    'Blackout Curtains',
                    'Sheer Curtains',
                    'Drapes',
                    'Valances',
                    'Curtain Rods',
                    'Curtain Rings',
                    'Curtain Hooks',
                    'Curtain Panels',
                    'Curtain Sets',
                ],
            },
            {
                id: 'rugs-mats',
                name: 'Rugs & Mats',
                items: [
                    'Area Rugs',
                    'Door Mats',
                    'Runner Rugs',
                    'Bathroom Rugs',
                    'Kitchen Rugs',
                    'Outdoor Rugs',
                    'Stair Runners',
                    'Carpet Runners',
                    'Anti-Fatigue Mats',
                    'Decorative Rugs',
                ],
            },
            {
                id: 'cushions-throws',
                name: 'Cushions & Throws',
                items: [
                    'Decorative Cushions',
                    'Floor Cushions',
                    'Outdoor Cushions',
                    'Throw Blankets',
                    'Decorative Throws',
                    'Cushion Covers',
                    'Pillow Covers',
                    'Cushion Sets',
                    'Throw Pillows',
                    'Accent Pillows',
                ],
            },
            {
                id: 'table-linens',
                name: 'Table Linens',
                items: [
                    'Tablecloths',
                    'Table Runners',
                    'Placemats',
                    'Napkins',
                    'Table Skirts',
                    'Table Toppers',
                    'Table Sets',
                    'Buffet Runners',
                    'Table Protectors',
                    'Table Accessories',
                ],
            },
            {
                id: 'window-treatments',
                name: 'Window Treatments',
                items: [
                    'Window Shades',
                    'Blinds',
                    'Roman Shades',
                    'Roller Shades',
                    'Window Valances',
                    'Window Scarves',
                    'Window Hardware',
                    'Window Accessories',
                    'Window Panels',
                    'Window Sets',
                ],
            },
        ],
    },
    {
        id: 'electronics',
        name: 'ELECTRONICS',
        subCategories: [
            {
                id: 'smart-home',
                name: 'Smart Home',
                items: [
                    'Smart Speakers',
                    'Smart Lights',
                    'Smart Plugs',
                    'Smart Thermostats',
                    'Security Cameras',
                    'Smart Locks',
                    'Smart Sensors',
                    'Smart Displays',
                    'Smart Hubs',
                    'Smart Home Kits',
                ],
            },
            {
                id: 'audio',
                name: 'Audio',
                items: [
                    'Wireless Earbuds',
                    'Headphones',
                    'Bluetooth Speakers',
                    'Sound Systems',
                    'Audio Accessories',
                    'Microphones',
                    'Audio Cables',
                    'Audio Adapters',
                    'Portable Speakers',
                    'Audio Components',
                ],
            },
            {
                id: 'charging',
                name: 'Charging',
                items: [
                    'Wireless Chargers',
                    'USB Cables',
                    'Power Banks',
                    'Wall Chargers',
                    'Car Chargers',
                    'Charging Stations',
                    'Charging Accessories',
                    'Solar Chargers',
                    'Battery Packs',
                    'Charging Kits',
                ],
            },
            {
                id: 'gadgets',
                name: 'Gadgets',
                items: [
                    'Fitness Trackers',
                    'Smart Watches',
                    'Digital Cameras',
                    'Action Cameras',
                    'Drones',
                    'VR Headsets',
                    'Gaming Accessories',
                    'Electronic Toys',
                    'Digital Notebooks',
                    'Tech Gadgets',
                ],
            },
        ],
    },
    {
        id: 'office-supplies',
        name: 'OFFICE SUPPLIES',
        subCategories: [
            {
                id: 'writing',
                name: 'Writing',
                items: [
                    'Pens',
                    'Pencils',
                    'Markers',
                    'Highlighters',
                    'Notebooks',
                    'Journals',
                    'Sticky Notes',
                    'Notepads',
                    'Writing Sets',
                    'Art Supplies',
                ],
            },
            {
                id: 'organization',
                name: 'Organization',
                items: [
                    'File Folders',
                    'Binders',
                    'Storage Boxes',
                    'Desk Organizers',
                    'Paper Trays',
                    'Label Makers',
                    'Storage Solutions',
                    'Filing Systems',
                    'Desk Accessories',
                    'Office Storage',
                ],
            },
            {
                id: 'paper',
                name: 'Paper',
                items: [
                    'Copy Paper',
                    'Cardstock',
                    'Sticky Notes',
                    'Envelopes',
                    'Greeting Cards',
                    'Art Paper',
                    'Photo Paper',
                    'Labels',
                    'Paper Pads',
                    'Paper Sets',
                ],
            },
            {
                id: 'desk-accessories',
                name: 'Desk Accessories',
                items: [
                    'Desk Lamps',
                    'Mouse Pads',
                    'Desk Mats',
                    'Monitor Stands',
                    'Desk Organizers',
                    'Cable Management',
                    'Desk Plants',
                    'Desk Clocks',
                    'Desk Sets',
                    'Ergonomic Accessories',
                ],
            },
        ],
    },
    {
        id: 'sports-outdoors',
        name: 'SPORTS & OUTDOORS',
        subCategories: [
            {
                id: 'fitness',
                name: 'Fitness',
                items: [
                    'Yoga Mats',
                    'Resistance Bands',
                    'Dumbbells',
                    'Exercise Balls',
                    'Fitness Trackers',
                    'Jump Ropes',
                    'Foam Rollers',
                    'Fitness Accessories',
                    'Workout Equipment',
                    'Fitness Kits',
                ],
            },
            {
                id: 'outdoor-gear',
                name: 'Outdoor Gear',
                items: [
                    'Camping Tents',
                    'Sleeping Bags',
                    'Backpacks',
                    'Hiking Boots',
                    'Camping Stoves',
                    'Water Bottles',
                    'Outdoor Clothing',
                    'Camping Accessories',
                    'Hiking Gear',
                    'Outdoor Kits',
                ],
            },
            {
                id: 'sports-equipment',
                name: 'Sports Equipment',
                items: [
                    'Balls',
                    'Rackets',
                    'Sports Nets',
                    'Sports Bags',
                    'Protective Gear',
                    'Training Equipment',
                    'Sports Accessories',
                    'Team Sports',
                    'Individual Sports',
                    'Sports Kits',
                ],
            },
            {
                id: 'outdoor-living',
                name: 'Outdoor Living',
                items: [
                    'Garden Tools',
                    'Outdoor Furniture',
                    'BBQ Grills',
                    'Outdoor Lighting',
                    'Garden Decor',
                    'Planters',
                    'Outdoor Storage',
                    'Patio Accessories',
                    'Outdoor Games',
                    'Garden Kits',
                ],
            },
        ],
    },
    {
        id: 'beauty-cosmetics',
        name: 'BEAUTY & COSMETICS',
        subCategories: [
            {
                id: 'makeup',
                name: 'Makeup',
                items: [
                    'Foundation',
                    'Concealer',
                    'Eyeshadow',
                    'Mascara',
                    'Lipstick',
                    'Blush',
                    'Bronzer',
                    'Makeup Brushes',
                    'Makeup Sets',
                    'Makeup Accessories',
                ],
            },
            {
                id: 'skincare',
                name: 'Skincare',
                items: [
                    'Cleansers',
                    'Moisturizers',
                    'Serums',
                    'Face Masks',
                    'Eye Creams',
                    'Sunscreen',
                    'Toners',
                    'Exfoliators',
                    'Skincare Sets',
                    'Skincare Tools',
                ],
            },
            {
                id: 'haircare',
                name: 'Haircare',
                items: [
                    'Shampoo',
                    'Conditioner',
                    'Hair Masks',
                    'Hair Oils',
                    'Hair Styling',
                    'Hair Tools',
                    'Hair Accessories',
                    'Hair Color',
                    'Hair Treatments',
                    'Haircare Sets',
                ],
            },
            {
                id: 'fragrances',
                name: 'Fragrances',
                items: [
                    'Perfumes',
                    'Colognes',
                    'Body Sprays',
                    'Essential Oils',
                    'Room Fragrances',
                    'Scented Candles',
                    'Fragrance Sets',
                    'Travel Fragrances',
                    'Fragrance Accessories',
                    'Gift Sets',
                ],
            },
        ],
    },
];
